### ISSUE TITLE
Add delete portfolio API

### ISSUE THREAD

**Issue by psandesh34** [psandesh34/visualizer#1]
URL(delete): `/portfolio`
- Should delete all records related to the `userId` provided in the `req.body`

**Comment by ezzio** [comment]
Hello psandesh
I think I can help you with this issue. Can you assign it for me?

**Comment by psandesh34** [comment]
> Hello psandesh I think I can help you with this issue. Can you assign it for me?

@ezzio Sure, here you go!

**Comment by ezzio** [comment]
#2 I have finished, please check my pull request

**Comment by psandesh34** [comment]
Great, merged!
